// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.1
// source: remote.proto

package common

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type RequestCode int32

const (
	RequestCode_PUT_KV_CONFIG                      RequestCode = 0
	RequestCode_GET_KV_CONFIG                      RequestCode = 1
	RequestCode_DELETE_KV_CONFIG                   RequestCode = 2
	RequestCode_QUERY_DATA_VERSION                 RequestCode = 3
	RequestCode_REGISTER_BROKER                    RequestCode = 4
	RequestCode_UNREGISTER_BROKER                  RequestCode = 5
	RequestCode_GET_ROUTEINFO_BY_TOPIC             RequestCode = 6
	RequestCode_GET_BROKER_CLUSTER_INFO            RequestCode = 7
	RequestCode_WIPE_WRITE_PERM_OF_BROKER          RequestCode = 8
	RequestCode_GET_ALL_TOPIC_LIST_FROM_NAMESERVER RequestCode = 9
	RequestCode_DELETE_TOPIC_IN_NAMESRV            RequestCode = 10
	RequestCode_GET_KVLIST_BY_NAMESPACE            RequestCode = 11
	RequestCode_GET_TOPICS_BY_CLUSTER              RequestCode = 12
	RequestCode_GET_SYSTEM_TOPIC_LIST_FROM_NS      RequestCode = 13
	RequestCode_GET_UNIT_TOPIC_LIST                RequestCode = 14
	RequestCode_GET_HAS_UNIT_SUB_TOPIC_LIST        RequestCode = 15
	RequestCode_GET_HAS_UNIT_SUB_UNUNIT_TOPIC_LIST RequestCode = 16
	RequestCode_UPDATE_NAMESRV_CONFIG              RequestCode = 17
	RequestCode_GET_NAMESRV_CONFIG                 RequestCode = 18
)

// Enum value maps for RequestCode.
var (
	RequestCode_name = map[int32]string{
		0:  "PUT_KV_CONFIG",
		1:  "GET_KV_CONFIG",
		2:  "DELETE_KV_CONFIG",
		3:  "QUERY_DATA_VERSION",
		4:  "REGISTER_BROKER",
		5:  "UNREGISTER_BROKER",
		6:  "GET_ROUTEINFO_BY_TOPIC",
		7:  "GET_BROKER_CLUSTER_INFO",
		8:  "WIPE_WRITE_PERM_OF_BROKER",
		9:  "GET_ALL_TOPIC_LIST_FROM_NAMESERVER",
		10: "DELETE_TOPIC_IN_NAMESRV",
		11: "GET_KVLIST_BY_NAMESPACE",
		12: "GET_TOPICS_BY_CLUSTER",
		13: "GET_SYSTEM_TOPIC_LIST_FROM_NS",
		14: "GET_UNIT_TOPIC_LIST",
		15: "GET_HAS_UNIT_SUB_TOPIC_LIST",
		16: "GET_HAS_UNIT_SUB_UNUNIT_TOPIC_LIST",
		17: "UPDATE_NAMESRV_CONFIG",
		18: "GET_NAMESRV_CONFIG",
	}
	RequestCode_value = map[string]int32{
		"PUT_KV_CONFIG":                      0,
		"GET_KV_CONFIG":                      1,
		"DELETE_KV_CONFIG":                   2,
		"QUERY_DATA_VERSION":                 3,
		"REGISTER_BROKER":                    4,
		"UNREGISTER_BROKER":                  5,
		"GET_ROUTEINFO_BY_TOPIC":             6,
		"GET_BROKER_CLUSTER_INFO":            7,
		"WIPE_WRITE_PERM_OF_BROKER":          8,
		"GET_ALL_TOPIC_LIST_FROM_NAMESERVER": 9,
		"DELETE_TOPIC_IN_NAMESRV":            10,
		"GET_KVLIST_BY_NAMESPACE":            11,
		"GET_TOPICS_BY_CLUSTER":              12,
		"GET_SYSTEM_TOPIC_LIST_FROM_NS":      13,
		"GET_UNIT_TOPIC_LIST":                14,
		"GET_HAS_UNIT_SUB_TOPIC_LIST":        15,
		"GET_HAS_UNIT_SUB_UNUNIT_TOPIC_LIST": 16,
		"UPDATE_NAMESRV_CONFIG":              17,
		"GET_NAMESRV_CONFIG":                 18,
	}
)

func (x RequestCode) Enum() *RequestCode {
	p := new(RequestCode)
	*p = x
	return p
}

func (x RequestCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestCode) Descriptor() protoreflect.EnumDescriptor {
	return file_remote_proto_enumTypes[0].Descriptor()
}

func (RequestCode) Type() protoreflect.EnumType {
	return &file_remote_proto_enumTypes[0]
}

func (x RequestCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestCode.Descriptor instead.
func (RequestCode) EnumDescriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{0}
}

type ResponseCode int32

const (
	ResponseCode_SUCCESS                    ResponseCode = 0
	ResponseCode_SYSTEM_ERROR               ResponseCode = 1
	ResponseCode_SYSTEM_BUSY                ResponseCode = 2
	ResponseCode_REQUEST_CODE_NOT_SUPPORTED ResponseCode = 3
	ResponseCode_TRANSACTION_FAILED         ResponseCode = 4
	ResponseCode_QUERY_NOT_FOUND            ResponseCode = 5
	ResponseCode_TOPIC_NOT_EXIST            ResponseCode = 6
)

// Enum value maps for ResponseCode.
var (
	ResponseCode_name = map[int32]string{
		0: "SUCCESS",
		1: "SYSTEM_ERROR",
		2: "SYSTEM_BUSY",
		3: "REQUEST_CODE_NOT_SUPPORTED",
		4: "TRANSACTION_FAILED",
		5: "QUERY_NOT_FOUND",
		6: "TOPIC_NOT_EXIST",
	}
	ResponseCode_value = map[string]int32{
		"SUCCESS":                    0,
		"SYSTEM_ERROR":               1,
		"SYSTEM_BUSY":                2,
		"REQUEST_CODE_NOT_SUPPORTED": 3,
		"TRANSACTION_FAILED":         4,
		"QUERY_NOT_FOUND":            5,
		"TOPIC_NOT_EXIST":            6,
	}
)

func (x ResponseCode) Enum() *ResponseCode {
	p := new(ResponseCode)
	*p = x
	return p
}

func (x ResponseCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseCode) Descriptor() protoreflect.EnumDescriptor {
	return file_remote_proto_enumTypes[1].Descriptor()
}

func (ResponseCode) Type() protoreflect.EnumType {
	return &file_remote_proto_enumTypes[1]
}

func (x ResponseCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseCode.Descriptor instead.
func (ResponseCode) EnumDescriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{1}
}

type RemoteCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version int32  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Code    int32  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Header  []byte `protobuf:"bytes,3,opt,name=header,proto3" json:"header,omitempty"`
	Body    []byte `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Remark  string `protobuf:"bytes,5,opt,name=remark,proto3" json:"remark,omitempty"`
}

func (x *RemoteCommand) Reset() {
	*x = RemoteCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remote_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoteCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteCommand) ProtoMessage() {}

func (x *RemoteCommand) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteCommand.ProtoReflect.Descriptor instead.
func (*RemoteCommand) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{0}
}

func (x *RemoteCommand) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RemoteCommand) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RemoteCommand) GetHeader() []byte {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *RemoteCommand) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *RemoteCommand) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

// PUT_KV_CONFIG
type PutKVConfigRequestHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Key       string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value     string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *PutKVConfigRequestHeader) Reset() {
	*x = PutKVConfigRequestHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remote_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutKVConfigRequestHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutKVConfigRequestHeader) ProtoMessage() {}

func (x *PutKVConfigRequestHeader) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutKVConfigRequestHeader.ProtoReflect.Descriptor instead.
func (*PutKVConfigRequestHeader) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{1}
}

func (x *PutKVConfigRequestHeader) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PutKVConfigRequestHeader) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutKVConfigRequestHeader) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// GET_KV_CONFIG
type GetKVConfigRequestHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Key       string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *GetKVConfigRequestHeader) Reset() {
	*x = GetKVConfigRequestHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remote_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetKVConfigRequestHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKVConfigRequestHeader) ProtoMessage() {}

func (x *GetKVConfigRequestHeader) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKVConfigRequestHeader.ProtoReflect.Descriptor instead.
func (*GetKVConfigRequestHeader) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{2}
}

func (x *GetKVConfigRequestHeader) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetKVConfigRequestHeader) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetKVConfigResponseHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *GetKVConfigResponseHeader) Reset() {
	*x = GetKVConfigResponseHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remote_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetKVConfigResponseHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKVConfigResponseHeader) ProtoMessage() {}

func (x *GetKVConfigResponseHeader) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKVConfigResponseHeader.ProtoReflect.Descriptor instead.
func (*GetKVConfigResponseHeader) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{3}
}

func (x *GetKVConfigResponseHeader) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// DELETE_KV_CONFIG
type DeleteKVConfigRequestHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Key       string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *DeleteKVConfigRequestHeader) Reset() {
	*x = DeleteKVConfigRequestHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remote_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteKVConfigRequestHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKVConfigRequestHeader) ProtoMessage() {}

func (x *DeleteKVConfigRequestHeader) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKVConfigRequestHeader.ProtoReflect.Descriptor instead.
func (*DeleteKVConfigRequestHeader) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteKVConfigRequestHeader) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DeleteKVConfigRequestHeader) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// QUERY_DATA_VERSION
type QueryDataVersionRequestHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BrokerName  string `protobuf:"bytes,1,opt,name=brokerName,proto3" json:"brokerName,omitempty"`
	BrokerAddr  string `protobuf:"bytes,2,opt,name=brokerAddr,proto3" json:"brokerAddr,omitempty"`
	ClusterName string `protobuf:"bytes,3,opt,name=clusterName,proto3" json:"clusterName,omitempty"`
	BrokerId    int64  `protobuf:"varint,4,opt,name=brokerId,proto3" json:"brokerId,omitempty"`
}

func (x *QueryDataVersionRequestHeader) Reset() {
	*x = QueryDataVersionRequestHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remote_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryDataVersionRequestHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryDataVersionRequestHeader) ProtoMessage() {}

func (x *QueryDataVersionRequestHeader) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryDataVersionRequestHeader.ProtoReflect.Descriptor instead.
func (*QueryDataVersionRequestHeader) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{5}
}

func (x *QueryDataVersionRequestHeader) GetBrokerName() string {
	if x != nil {
		return x.BrokerName
	}
	return ""
}

func (x *QueryDataVersionRequestHeader) GetBrokerAddr() string {
	if x != nil {
		return x.BrokerAddr
	}
	return ""
}

func (x *QueryDataVersionRequestHeader) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *QueryDataVersionRequestHeader) GetBrokerId() int64 {
	if x != nil {
		return x.BrokerId
	}
	return 0
}

type QueryDataVersionResponseHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Changed bool `protobuf:"varint,1,opt,name=changed,proto3" json:"changed,omitempty"`
}

func (x *QueryDataVersionResponseHeader) Reset() {
	*x = QueryDataVersionResponseHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remote_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryDataVersionResponseHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryDataVersionResponseHeader) ProtoMessage() {}

func (x *QueryDataVersionResponseHeader) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryDataVersionResponseHeader.ProtoReflect.Descriptor instead.
func (*QueryDataVersionResponseHeader) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{6}
}

func (x *QueryDataVersionResponseHeader) GetChanged() bool {
	if x != nil {
		return x.Changed
	}
	return false
}

// REGISTER_BROKER
type RegisterBrokerRequestHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BrokerName   string `protobuf:"bytes,1,opt,name=brokerName,proto3" json:"brokerName,omitempty"`
	BrokerAddr   string `protobuf:"bytes,2,opt,name=brokerAddr,proto3" json:"brokerAddr,omitempty"`
	ClusterName  string `protobuf:"bytes,3,opt,name=clusterName,proto3" json:"clusterName,omitempty"`
	HaServerAddr string `protobuf:"bytes,4,opt,name=haServerAddr,proto3" json:"haServerAddr,omitempty"`
	BrokerId     int64  `protobuf:"varint,5,opt,name=brokerId,proto3" json:"brokerId,omitempty"`
	Compressed   bool   `protobuf:"varint,6,opt,name=compressed,proto3" json:"compressed,omitempty"`
	BodyCrc32    int32  `protobuf:"varint,7,opt,name=bodyCrc32,proto3" json:"bodyCrc32,omitempty"`
}

func (x *RegisterBrokerRequestHeader) Reset() {
	*x = RegisterBrokerRequestHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remote_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterBrokerRequestHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterBrokerRequestHeader) ProtoMessage() {}

func (x *RegisterBrokerRequestHeader) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterBrokerRequestHeader.ProtoReflect.Descriptor instead.
func (*RegisterBrokerRequestHeader) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterBrokerRequestHeader) GetBrokerName() string {
	if x != nil {
		return x.BrokerName
	}
	return ""
}

func (x *RegisterBrokerRequestHeader) GetBrokerAddr() string {
	if x != nil {
		return x.BrokerAddr
	}
	return ""
}

func (x *RegisterBrokerRequestHeader) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *RegisterBrokerRequestHeader) GetHaServerAddr() string {
	if x != nil {
		return x.HaServerAddr
	}
	return ""
}

func (x *RegisterBrokerRequestHeader) GetBrokerId() int64 {
	if x != nil {
		return x.BrokerId
	}
	return 0
}

func (x *RegisterBrokerRequestHeader) GetCompressed() bool {
	if x != nil {
		return x.Compressed
	}
	return false
}

func (x *RegisterBrokerRequestHeader) GetBodyCrc32() int32 {
	if x != nil {
		return x.BodyCrc32
	}
	return 0
}

type RegisterBrokerResponseHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HaServerAddr string `protobuf:"bytes,1,opt,name=haServerAddr,proto3" json:"haServerAddr,omitempty"`
	MasterAddr   string `protobuf:"bytes,2,opt,name=masterAddr,proto3" json:"masterAddr,omitempty"`
}

func (x *RegisterBrokerResponseHeader) Reset() {
	*x = RegisterBrokerResponseHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remote_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterBrokerResponseHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterBrokerResponseHeader) ProtoMessage() {}

func (x *RegisterBrokerResponseHeader) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterBrokerResponseHeader.ProtoReflect.Descriptor instead.
func (*RegisterBrokerResponseHeader) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{8}
}

func (x *RegisterBrokerResponseHeader) GetHaServerAddr() string {
	if x != nil {
		return x.HaServerAddr
	}
	return ""
}

func (x *RegisterBrokerResponseHeader) GetMasterAddr() string {
	if x != nil {
		return x.MasterAddr
	}
	return ""
}

type RegisterBrokerBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilterServerList []string `protobuf:"bytes,1,rep,name=filterServerList,proto3" json:"filterServerList,omitempty"`
}

func (x *RegisterBrokerBody) Reset() {
	*x = RegisterBrokerBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remote_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterBrokerBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterBrokerBody) ProtoMessage() {}

func (x *RegisterBrokerBody) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterBrokerBody.ProtoReflect.Descriptor instead.
func (*RegisterBrokerBody) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{9}
}

func (x *RegisterBrokerBody) GetFilterServerList() []string {
	if x != nil {
		return x.FilterServerList
	}
	return nil
}

// UNREGISTER_BROKER
type UnRegisterBrokerHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BrokerName  string `protobuf:"bytes,1,opt,name=brokerName,proto3" json:"brokerName,omitempty"`
	BrokerAddr  string `protobuf:"bytes,2,opt,name=brokerAddr,proto3" json:"brokerAddr,omitempty"`
	ClusterName string `protobuf:"bytes,3,opt,name=clusterName,proto3" json:"clusterName,omitempty"`
	BrokerId    int64  `protobuf:"varint,4,opt,name=brokerId,proto3" json:"brokerId,omitempty"`
}

func (x *UnRegisterBrokerHeader) Reset() {
	*x = UnRegisterBrokerHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remote_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnRegisterBrokerHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnRegisterBrokerHeader) ProtoMessage() {}

func (x *UnRegisterBrokerHeader) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnRegisterBrokerHeader.ProtoReflect.Descriptor instead.
func (*UnRegisterBrokerHeader) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{10}
}

func (x *UnRegisterBrokerHeader) GetBrokerName() string {
	if x != nil {
		return x.BrokerName
	}
	return ""
}

func (x *UnRegisterBrokerHeader) GetBrokerAddr() string {
	if x != nil {
		return x.BrokerAddr
	}
	return ""
}

func (x *UnRegisterBrokerHeader) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *UnRegisterBrokerHeader) GetBrokerId() int64 {
	if x != nil {
		return x.BrokerId
	}
	return 0
}

// GET_ROUTEINFO_BY_TOPIC
type GetRouteInfoRequestHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
}

func (x *GetRouteInfoRequestHeader) Reset() {
	*x = GetRouteInfoRequestHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remote_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRouteInfoRequestHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRouteInfoRequestHeader) ProtoMessage() {}

func (x *GetRouteInfoRequestHeader) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRouteInfoRequestHeader.ProtoReflect.Descriptor instead.
func (*GetRouteInfoRequestHeader) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{11}
}

func (x *GetRouteInfoRequestHeader) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

// WIPE_WRITE_PERM_OF_BROKER
type WipeWritePermOfBrokerRequestHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BrokerName string `protobuf:"bytes,1,opt,name=brokerName,proto3" json:"brokerName,omitempty"`
}

func (x *WipeWritePermOfBrokerRequestHeader) Reset() {
	*x = WipeWritePermOfBrokerRequestHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remote_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WipeWritePermOfBrokerRequestHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WipeWritePermOfBrokerRequestHeader) ProtoMessage() {}

func (x *WipeWritePermOfBrokerRequestHeader) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WipeWritePermOfBrokerRequestHeader.ProtoReflect.Descriptor instead.
func (*WipeWritePermOfBrokerRequestHeader) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{12}
}

func (x *WipeWritePermOfBrokerRequestHeader) GetBrokerName() string {
	if x != nil {
		return x.BrokerName
	}
	return ""
}

type WipeWritePermOfBrokerResponseHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WipeTopicCount int32 `protobuf:"varint,1,opt,name=wipeTopicCount,proto3" json:"wipeTopicCount,omitempty"`
}

func (x *WipeWritePermOfBrokerResponseHeader) Reset() {
	*x = WipeWritePermOfBrokerResponseHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remote_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WipeWritePermOfBrokerResponseHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WipeWritePermOfBrokerResponseHeader) ProtoMessage() {}

func (x *WipeWritePermOfBrokerResponseHeader) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WipeWritePermOfBrokerResponseHeader.ProtoReflect.Descriptor instead.
func (*WipeWritePermOfBrokerResponseHeader) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{13}
}

func (x *WipeWritePermOfBrokerResponseHeader) GetWipeTopicCount() int32 {
	if x != nil {
		return x.WipeTopicCount
	}
	return 0
}

// DELETE_TOPIC_IN_NAMESRV
type DeleteTopicInNamesrvRequestHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
}

func (x *DeleteTopicInNamesrvRequestHeader) Reset() {
	*x = DeleteTopicInNamesrvRequestHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remote_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTopicInNamesrvRequestHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTopicInNamesrvRequestHeader) ProtoMessage() {}

func (x *DeleteTopicInNamesrvRequestHeader) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTopicInNamesrvRequestHeader.ProtoReflect.Descriptor instead.
func (*DeleteTopicInNamesrvRequestHeader) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteTopicInNamesrvRequestHeader) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

// GET_KVLIST_BY_NAMESPACE
type GetKVListByNamespaceRequestHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
}

func (x *GetKVListByNamespaceRequestHeader) Reset() {
	*x = GetKVListByNamespaceRequestHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remote_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetKVListByNamespaceRequestHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKVListByNamespaceRequestHeader) ProtoMessage() {}

func (x *GetKVListByNamespaceRequestHeader) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKVListByNamespaceRequestHeader.ProtoReflect.Descriptor instead.
func (*GetKVListByNamespaceRequestHeader) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{15}
}

func (x *GetKVListByNamespaceRequestHeader) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

// GET_TOPICS_BY_CLUSTER
type GetTopicsByClusterRequestHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cluster string `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
}

func (x *GetTopicsByClusterRequestHeader) Reset() {
	*x = GetTopicsByClusterRequestHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remote_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTopicsByClusterRequestHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopicsByClusterRequestHeader) ProtoMessage() {}

func (x *GetTopicsByClusterRequestHeader) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopicsByClusterRequestHeader.ProtoReflect.Descriptor instead.
func (*GetTopicsByClusterRequestHeader) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{16}
}

func (x *GetTopicsByClusterRequestHeader) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

var File_remote_proto protoreflect.FileDescriptor

var file_remote_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x22, 0x81, 0x01, 0x0a, 0x0d, 0x52, 0x65, 0x6d, 0x6f, 0x74,
	0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f,
	0x64, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x22, 0x60, 0x0a, 0x18, 0x50, 0x75,
	0x74, 0x4b, 0x56, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x4a, 0x0a, 0x18,
	0x47, 0x65, 0x74, 0x4b, 0x56, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d,
	0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x31, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x4b,
	0x56, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x4d, 0x0a, 0x1b, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x56, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61,
	0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e,
	0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x9d, 0x01, 0x0a, 0x1d, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x44, 0x61, 0x74, 0x61, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a,
	0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a,
	0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x12, 0x20, 0x0a, 0x0b,
	0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x49, 0x64, 0x22, 0x3a, 0x0a, 0x1e, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x44, 0x61, 0x74, 0x61, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x63,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x22, 0xfd, 0x01, 0x0a, 0x1b, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x72, 0x6f, 0x6b,
	0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72,
	0x41, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x72, 0x6f, 0x6b,
	0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65,
	0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6c, 0x75,
	0x73, 0x74, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x68, 0x61, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x68, 0x61, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x12, 0x1a, 0x0a, 0x08,
	0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x70,
	0x72, 0x65, 0x73, 0x73, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x63, 0x6f,
	0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x65, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x6f, 0x64, 0x79,
	0x43, 0x72, 0x63, 0x33, 0x32, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x62, 0x6f, 0x64,
	0x79, 0x43, 0x72, 0x63, 0x33, 0x32, 0x22, 0x62, 0x0a, 0x1c, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x0c, 0x68, 0x61, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x68, 0x61,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x61,
	0x73, 0x74, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x22, 0x40, 0x0a, 0x12, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x42, 0x6f, 0x64, 0x79,
	0x12, 0x2a, 0x0a, 0x10, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x10, 0x66, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x96, 0x01, 0x0a,
	0x16, 0x55, 0x6e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x42, 0x72, 0x6f, 0x6b, 0x65,
	0x72, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x72, 0x6f, 0x6b, 0x65,
	0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x72, 0x6f,
	0x6b, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x72, 0x6f, 0x6b, 0x65,
	0x72, 0x41, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x72, 0x6f,
	0x6b, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6c, 0x75, 0x73, 0x74,
	0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6c,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x72, 0x6f,
	0x6b, 0x65, 0x72, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x62, 0x72, 0x6f,
	0x6b, 0x65, 0x72, 0x49, 0x64, 0x22, 0x31, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x75, 0x74,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x22, 0x44, 0x0a, 0x22, 0x57, 0x69, 0x70, 0x65,
	0x57, 0x72, 0x69, 0x74, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x4f, 0x66, 0x42, 0x72, 0x6f, 0x6b, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x1e,
	0x0a, 0x0a, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x4d,
	0x0a, 0x23, 0x57, 0x69, 0x70, 0x65, 0x57, 0x72, 0x69, 0x74, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x4f,
	0x66, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x26, 0x0a, 0x0e, 0x77, 0x69, 0x70, 0x65, 0x54, 0x6f, 0x70,
	0x69, 0x63, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x77,
	0x69, 0x70, 0x65, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x39, 0x0a,
	0x21, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x49, 0x6e, 0x4e, 0x61,
	0x6d, 0x65, 0x73, 0x72, 0x76, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x22, 0x41, 0x0a, 0x21, 0x47, 0x65, 0x74, 0x4b,
	0x56, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x1c, 0x0a,
	0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x22, 0x3b, 0x0a, 0x1f, 0x47,
	0x65, 0x74, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x42, 0x79, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2a, 0x9a, 0x04, 0x0a, 0x0b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x11, 0x0a, 0x0d, 0x50, 0x55, 0x54, 0x5f,
	0x4b, 0x56, 0x5f, 0x43, 0x4f, 0x4e, 0x46, 0x49, 0x47, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x47,
	0x45, 0x54, 0x5f, 0x4b, 0x56, 0x5f, 0x43, 0x4f, 0x4e, 0x46, 0x49, 0x47, 0x10, 0x01, 0x12, 0x14,
	0x0a, 0x10, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x5f, 0x4b, 0x56, 0x5f, 0x43, 0x4f, 0x4e, 0x46,
	0x49, 0x47, 0x10, 0x02, 0x12, 0x16, 0x0a, 0x12, 0x51, 0x55, 0x45, 0x52, 0x59, 0x5f, 0x44, 0x41,
	0x54, 0x41, 0x5f, 0x56, 0x45, 0x52, 0x53, 0x49, 0x4f, 0x4e, 0x10, 0x03, 0x12, 0x13, 0x0a, 0x0f,
	0x52, 0x45, 0x47, 0x49, 0x53, 0x54, 0x45, 0x52, 0x5f, 0x42, 0x52, 0x4f, 0x4b, 0x45, 0x52, 0x10,
	0x04, 0x12, 0x15, 0x0a, 0x11, 0x55, 0x4e, 0x52, 0x45, 0x47, 0x49, 0x53, 0x54, 0x45, 0x52, 0x5f,
	0x42, 0x52, 0x4f, 0x4b, 0x45, 0x52, 0x10, 0x05, 0x12, 0x1a, 0x0a, 0x16, 0x47, 0x45, 0x54, 0x5f,
	0x52, 0x4f, 0x55, 0x54, 0x45, 0x49, 0x4e, 0x46, 0x4f, 0x5f, 0x42, 0x59, 0x5f, 0x54, 0x4f, 0x50,
	0x49, 0x43, 0x10, 0x06, 0x12, 0x1b, 0x0a, 0x17, 0x47, 0x45, 0x54, 0x5f, 0x42, 0x52, 0x4f, 0x4b,
	0x45, 0x52, 0x5f, 0x43, 0x4c, 0x55, 0x53, 0x54, 0x45, 0x52, 0x5f, 0x49, 0x4e, 0x46, 0x4f, 0x10,
	0x07, 0x12, 0x1d, 0x0a, 0x19, 0x57, 0x49, 0x50, 0x45, 0x5f, 0x57, 0x52, 0x49, 0x54, 0x45, 0x5f,
	0x50, 0x45, 0x52, 0x4d, 0x5f, 0x4f, 0x46, 0x5f, 0x42, 0x52, 0x4f, 0x4b, 0x45, 0x52, 0x10, 0x08,
	0x12, 0x26, 0x0a, 0x22, 0x47, 0x45, 0x54, 0x5f, 0x41, 0x4c, 0x4c, 0x5f, 0x54, 0x4f, 0x50, 0x49,
	0x43, 0x5f, 0x4c, 0x49, 0x53, 0x54, 0x5f, 0x46, 0x52, 0x4f, 0x4d, 0x5f, 0x4e, 0x41, 0x4d, 0x45,
	0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x10, 0x09, 0x12, 0x1b, 0x0a, 0x17, 0x44, 0x45, 0x4c, 0x45,
	0x54, 0x45, 0x5f, 0x54, 0x4f, 0x50, 0x49, 0x43, 0x5f, 0x49, 0x4e, 0x5f, 0x4e, 0x41, 0x4d, 0x45,
	0x53, 0x52, 0x56, 0x10, 0x0a, 0x12, 0x1b, 0x0a, 0x17, 0x47, 0x45, 0x54, 0x5f, 0x4b, 0x56, 0x4c,
	0x49, 0x53, 0x54, 0x5f, 0x42, 0x59, 0x5f, 0x4e, 0x41, 0x4d, 0x45, 0x53, 0x50, 0x41, 0x43, 0x45,
	0x10, 0x0b, 0x12, 0x19, 0x0a, 0x15, 0x47, 0x45, 0x54, 0x5f, 0x54, 0x4f, 0x50, 0x49, 0x43, 0x53,
	0x5f, 0x42, 0x59, 0x5f, 0x43, 0x4c, 0x55, 0x53, 0x54, 0x45, 0x52, 0x10, 0x0c, 0x12, 0x21, 0x0a,
	0x1d, 0x47, 0x45, 0x54, 0x5f, 0x53, 0x59, 0x53, 0x54, 0x45, 0x4d, 0x5f, 0x54, 0x4f, 0x50, 0x49,
	0x43, 0x5f, 0x4c, 0x49, 0x53, 0x54, 0x5f, 0x46, 0x52, 0x4f, 0x4d, 0x5f, 0x4e, 0x53, 0x10, 0x0d,
	0x12, 0x17, 0x0a, 0x13, 0x47, 0x45, 0x54, 0x5f, 0x55, 0x4e, 0x49, 0x54, 0x5f, 0x54, 0x4f, 0x50,
	0x49, 0x43, 0x5f, 0x4c, 0x49, 0x53, 0x54, 0x10, 0x0e, 0x12, 0x1f, 0x0a, 0x1b, 0x47, 0x45, 0x54,
	0x5f, 0x48, 0x41, 0x53, 0x5f, 0x55, 0x4e, 0x49, 0x54, 0x5f, 0x53, 0x55, 0x42, 0x5f, 0x54, 0x4f,
	0x50, 0x49, 0x43, 0x5f, 0x4c, 0x49, 0x53, 0x54, 0x10, 0x0f, 0x12, 0x26, 0x0a, 0x22, 0x47, 0x45,
	0x54, 0x5f, 0x48, 0x41, 0x53, 0x5f, 0x55, 0x4e, 0x49, 0x54, 0x5f, 0x53, 0x55, 0x42, 0x5f, 0x55,
	0x4e, 0x55, 0x4e, 0x49, 0x54, 0x5f, 0x54, 0x4f, 0x50, 0x49, 0x43, 0x5f, 0x4c, 0x49, 0x53, 0x54,
	0x10, 0x10, 0x12, 0x19, 0x0a, 0x15, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x5f, 0x4e, 0x41, 0x4d,
	0x45, 0x53, 0x52, 0x56, 0x5f, 0x43, 0x4f, 0x4e, 0x46, 0x49, 0x47, 0x10, 0x11, 0x12, 0x16, 0x0a,
	0x12, 0x47, 0x45, 0x54, 0x5f, 0x4e, 0x41, 0x4d, 0x45, 0x53, 0x52, 0x56, 0x5f, 0x43, 0x4f, 0x4e,
	0x46, 0x49, 0x47, 0x10, 0x12, 0x2a, 0xa0, 0x01, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53,
	0x53, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x59, 0x53, 0x54, 0x45, 0x4d, 0x5f, 0x45, 0x52,
	0x52, 0x4f, 0x52, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x59, 0x53, 0x54, 0x45, 0x4d, 0x5f,
	0x42, 0x55, 0x53, 0x59, 0x10, 0x02, 0x12, 0x1e, 0x0a, 0x1a, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53,
	0x54, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x53, 0x55, 0x50, 0x50, 0x4f,
	0x52, 0x54, 0x45, 0x44, 0x10, 0x03, 0x12, 0x16, 0x0a, 0x12, 0x54, 0x52, 0x41, 0x4e, 0x53, 0x41,
	0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x04, 0x12, 0x13,
	0x0a, 0x0f, 0x51, 0x55, 0x45, 0x52, 0x59, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e,
	0x44, 0x10, 0x05, 0x12, 0x13, 0x0a, 0x0f, 0x54, 0x4f, 0x50, 0x49, 0x43, 0x5f, 0x4e, 0x4f, 0x54,
	0x5f, 0x45, 0x58, 0x49, 0x53, 0x54, 0x10, 0x06, 0x32, 0x4a, 0x0a, 0x09, 0x52, 0x65, 0x6d, 0x6f,
	0x74, 0x65, 0x52, 0x50, 0x43, 0x12, 0x3d, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x12, 0x15, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x1a, 0x15, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x00,
	0x28, 0x01, 0x30, 0x01, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x3b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_remote_proto_rawDescOnce sync.Once
	file_remote_proto_rawDescData = file_remote_proto_rawDesc
)

func file_remote_proto_rawDescGZIP() []byte {
	file_remote_proto_rawDescOnce.Do(func() {
		file_remote_proto_rawDescData = protoimpl.X.CompressGZIP(file_remote_proto_rawDescData)
	})
	return file_remote_proto_rawDescData
}

var file_remote_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_remote_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_remote_proto_goTypes = []interface{}{
	(RequestCode)(0),                            // 0: common.RequestCode
	(ResponseCode)(0),                           // 1: common.ResponseCode
	(*RemoteCommand)(nil),                       // 2: common.RemoteCommand
	(*PutKVConfigRequestHeader)(nil),            // 3: common.PutKVConfigRequestHeader
	(*GetKVConfigRequestHeader)(nil),            // 4: common.GetKVConfigRequestHeader
	(*GetKVConfigResponseHeader)(nil),           // 5: common.GetKVConfigResponseHeader
	(*DeleteKVConfigRequestHeader)(nil),         // 6: common.DeleteKVConfigRequestHeader
	(*QueryDataVersionRequestHeader)(nil),       // 7: common.QueryDataVersionRequestHeader
	(*QueryDataVersionResponseHeader)(nil),      // 8: common.QueryDataVersionResponseHeader
	(*RegisterBrokerRequestHeader)(nil),         // 9: common.RegisterBrokerRequestHeader
	(*RegisterBrokerResponseHeader)(nil),        // 10: common.RegisterBrokerResponseHeader
	(*RegisterBrokerBody)(nil),                  // 11: common.RegisterBrokerBody
	(*UnRegisterBrokerHeader)(nil),              // 12: common.UnRegisterBrokerHeader
	(*GetRouteInfoRequestHeader)(nil),           // 13: common.GetRouteInfoRequestHeader
	(*WipeWritePermOfBrokerRequestHeader)(nil),  // 14: common.WipeWritePermOfBrokerRequestHeader
	(*WipeWritePermOfBrokerResponseHeader)(nil), // 15: common.WipeWritePermOfBrokerResponseHeader
	(*DeleteTopicInNamesrvRequestHeader)(nil),   // 16: common.DeleteTopicInNamesrvRequestHeader
	(*GetKVListByNamespaceRequestHeader)(nil),   // 17: common.GetKVListByNamespaceRequestHeader
	(*GetTopicsByClusterRequestHeader)(nil),     // 18: common.GetTopicsByClusterRequestHeader
}
var file_remote_proto_depIdxs = []int32{
	2, // 0: common.RemoteRPC.Process:input_type -> common.RemoteCommand
	2, // 1: common.RemoteRPC.Process:output_type -> common.RemoteCommand
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_remote_proto_init() }
func file_remote_proto_init() {
	if File_remote_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_remote_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoteCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remote_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutKVConfigRequestHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remote_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetKVConfigRequestHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remote_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetKVConfigResponseHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remote_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteKVConfigRequestHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remote_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryDataVersionRequestHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remote_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryDataVersionResponseHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remote_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterBrokerRequestHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remote_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterBrokerResponseHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remote_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterBrokerBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remote_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnRegisterBrokerHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remote_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRouteInfoRequestHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remote_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WipeWritePermOfBrokerRequestHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remote_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WipeWritePermOfBrokerResponseHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remote_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTopicInNamesrvRequestHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remote_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetKVListByNamespaceRequestHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remote_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTopicsByClusterRequestHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_remote_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_remote_proto_goTypes,
		DependencyIndexes: file_remote_proto_depIdxs,
		EnumInfos:         file_remote_proto_enumTypes,
		MessageInfos:      file_remote_proto_msgTypes,
	}.Build()
	File_remote_proto = out.File
	file_remote_proto_rawDesc = nil
	file_remote_proto_goTypes = nil
	file_remote_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RemoteRPCClient is the client API for RemoteRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RemoteRPCClient interface {
	Process(ctx context.Context, opts ...grpc.CallOption) (RemoteRPC_ProcessClient, error)
}

type remoteRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewRemoteRPCClient(cc grpc.ClientConnInterface) RemoteRPCClient {
	return &remoteRPCClient{cc}
}

func (c *remoteRPCClient) Process(ctx context.Context, opts ...grpc.CallOption) (RemoteRPC_ProcessClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RemoteRPC_serviceDesc.Streams[0], "/common.RemoteRPC/Process", opts...)
	if err != nil {
		return nil, err
	}
	x := &remoteRPCProcessClient{stream}
	return x, nil
}

type RemoteRPC_ProcessClient interface {
	Send(*RemoteCommand) error
	Recv() (*RemoteCommand, error)
	grpc.ClientStream
}

type remoteRPCProcessClient struct {
	grpc.ClientStream
}

func (x *remoteRPCProcessClient) Send(m *RemoteCommand) error {
	return x.ClientStream.SendMsg(m)
}

func (x *remoteRPCProcessClient) Recv() (*RemoteCommand, error) {
	m := new(RemoteCommand)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RemoteRPCServer is the server API for RemoteRPC service.
type RemoteRPCServer interface {
	Process(RemoteRPC_ProcessServer) error
}

// UnimplementedRemoteRPCServer can be embedded to have forward compatible implementations.
type UnimplementedRemoteRPCServer struct {
}

func (*UnimplementedRemoteRPCServer) Process(RemoteRPC_ProcessServer) error {
	return status.Errorf(codes.Unimplemented, "method Process not implemented")
}

func RegisterRemoteRPCServer(s *grpc.Server, srv RemoteRPCServer) {
	s.RegisterService(&_RemoteRPC_serviceDesc, srv)
}

func _RemoteRPC_Process_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RemoteRPCServer).Process(&remoteRPCProcessServer{stream})
}

type RemoteRPC_ProcessServer interface {
	Send(*RemoteCommand) error
	Recv() (*RemoteCommand, error)
	grpc.ServerStream
}

type remoteRPCProcessServer struct {
	grpc.ServerStream
}

func (x *remoteRPCProcessServer) Send(m *RemoteCommand) error {
	return x.ServerStream.SendMsg(m)
}

func (x *remoteRPCProcessServer) Recv() (*RemoteCommand, error) {
	m := new(RemoteCommand)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _RemoteRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "common.RemoteRPC",
	HandlerType: (*RemoteRPCServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Process",
			Handler:       _RemoteRPC_Process_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "remote.proto",
}
